name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: TELEGRAM_GROUP_ID,BOT_NAME,BOT_TOKEN,OPEN_AI_TOKEN,OPEN_AI_BASE_URL,BOT_DOMAIN,BOT_PORT
          script: |
            export TELEGRAM_GROUP_ID=${{ secrets.TELEGRAM_GROUP_ID }}
            export BOT_NAME=${{ secrets.BOT_NAME }}
            export BOT_TOKEN=${{ secrets.BOT_TOKEN}}
            export OPEN_AI_TOKEN=${{ secrets.OPEN_AI_TOKEN }}
            export OPEN_AI_BASE_URL=${{ secrets.OPEN_AI_BASE_URL }}
            export BOT_DOMAIN=${{ secrets.BOT_DOMAIN }}
            export BOT_PORT=${{ secrets.BOT_PORT }}
            cd telegram-bot
            pwd
            sh deploy.sh